version: "3.4"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9900:9900
